export enum SectionType {
    HERO_BANNER = "HERO_BANNER",
    CATEGORY_SLIDER = "CATEGORY_SLIDER",
    PRODUCT_CAROUSEL = "PRODUCT_CAROUSEL",
    PRODUCT_GRID = "PRODUCT_GRID",
    PROMOTION_BANNER = "PROMOTION_BANNER",
    BRAND_SLIDER = "BRAND_SLIDER",
    FLASH_SALE = "FLASH_SALE",
    OFFER_STRIP = "OFFER_STRIP",
    SELLER_BANNER = "SELLER_BANNER",
    RECENTLY_VIEWED = "RECENTLY_VIEWED"
}